name: Terraform Destroy

on:
  workflow_dispatch: # Manually triggered

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      # Replace secrets 
      - name: Replace secret in Terraform file
        run: |
          sed -i 's|VM_PASSWORD|'"${{ secrets.VM_PASSWORD }}"'|g' virtual_machine.tf
          sed -i 's|TF_RG_NAME|'"${{ secrets.TF_RG_NAME }}"'|g' main.tf
          sed -i 's|TF_SA_NAME|'"${{ secrets.TF_SA_NAME }}"'|g' main.tf
          sed -i 's|TF_CONT_NAME|'"${{ secrets.TF_CONT_NAME }}"'|g' main.tf
      
        # Terraform Init        
      - name: Terraform Init
        run: terraform init

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve